services:
  - type: cron
    name: vbpl-scraper-job
    runtime: python
    schedule: "0 0 1 * *"  # Run on the 1st of each month
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: python scrape_vbpl.py
